services:
  ros2:
    command: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    network_mode: "host"
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8087:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_BUCKET=mybucket
      - INFLUXDB_ORG=myorg

volumes:
  influxdb_data:
